title: Site
unlisted: true

columns:
  # main
  main:
    width: 2/3
    sections:
      # a list of the pages
      pages:
        type: pages
        headline: Pages

  # sidebar
  sidebar:
    width: 1/3
    sections:
    fields:
      NoIndex:
        label: Web Indexing
        type: toggle
        text:
            No
            Yes